name: mc-silica
author: PuckiSilver
description: Dynamic cooldown display
version: v1.0.0
output: build
require:
  - bolt

data_pack:
  name: mc-silica-dp
  load: src

resource_pack:
  name: mc-silica
  load: src

pipeline:
  - mecha
  - plugins.silica.generateOverlay

meta:
  bolt:
    entrypoint: silica:main
  mc-silica:
    - size: [16, 16]
      cdMax: 5.8
      shape: linear
      save: minecraft:item/overlay3
    - size: [128, 128]
      cdMax: 5.8
      shape: plugins/gradient_300x300.png
      save: minecraft:item/overlay2
