name: mc-silica
author: PuckiSilver
description: Dynamic cooldown display
version: v1.0.0
output: build
require:
  - bolt

data_pack:
  name: mc-silica-dp
  load: src

resource_pack:
  name: mc-silica-rp
  load: src

pipeline:
  - mecha

meta:
  bolt:
    entrypoint: silica:main
