name: mc-silica
author: PuckiSilver
description: Dynamic cooldown display
version: v1.0.0
output: build
require:
  - bolt

data_pack:
  name: mc-silica-dp
  load: src

resource_pack:
  name: mc-silica
  load: src

pipeline:
  - mecha
  - plugins.silica.generateTexture
  - plugins.silica.generateModel

meta:
  bolt:
    entrypoint: silica:main
  mc-silica:
    textures:
      - size: [128, 128]
        cdMax: 5.8
        shape: plugins/gradient_300x300.png
        path: minecraft:item/overlay2
    models:
      - path: minecraft:item/leather_horse_armor
        overlay: minecraft:item/overlay
